name: Syncs trunk with wordpress core trunk
on:
    schedule:
        # Run at every 15 minutes
        - cron: '*/15 * * * *'
    workflow_dispatch:
jobs:
    update-with-wp-core:
        runs-on: ubuntu-latest
        name: "Update with WP Core"
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - id: add-git-remote
              run: |
                  prs=$(gh pr list)
                  printf "The list of pull requests:\n%s\n" "${prs}"
                  #which branch are we on? should be main
                  #git branch -a
                  #git remote add wpcore https://github.com/gilzow/wpptest2.git
                  #git remote -v
                  #git remote update
            - id: remote-update
              run: |
                  prs=$(gh pr status)
                  printf "Current status of pull requests:\n%s\n" "${prs}"
                  #git remote update
            - id: check-status
              env:
                  #GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIT_EMAIL: ${{ secrets.GH_EMAIL }}
                  GIT_USER: ${{ secrets.GH_USER }}
              run: |
                  updates=$(git log main..wpcore/main --oneline)
                  if [[ -n "${updates}" ]]; then
                    echo "::notice::Updates are available"
                    git config --global user.email "$GIT_EMAIL"
                    git config --global user.name "$GIT_USER"
                    git pull wpcore main --no-rebase --no-edit
                    git push origin main
                    echo "::notice::Main updated from wptest2 main"
                  else
                    echo "::notice::No updates right now."
                  fi
